meta_product_name: "Happy 1000"
meta_title: "Happy 1000 - Organise facilement tes repas !"
meta_description: "Happy 1000© c'est l'application avec un grand A qui te permet d'organiser de manière hyper simple
tes repas. Fini les discussions à ralonge sur messenger pour savoir où, quand et qui vient, tout est centralisé.
Tu sais ce qu'il faut rapporter pour le repas et qui apporte quoi. Cherry on the cake, tu sais combien tu paies à la fin et de manière équitable !
Les petits filous qui ne payaient jamais passeront eux aussi à la caisse ! Sorry not sorry ;)"
meta_image: "happy_1000_logo.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
